### ISSUE TITLE
Force more button to appear inline

### ISSUE THREAD

**Issue by T0miii** [jedfoster/Readmore.js#126]
Hi Jed,

is it possible to position the more and less link inline?
I tried to use 'display: inline' for both link and block, but then
plugin seem to be not working anymore.

Thanks for your help!
Tomi

**Comment by rashagen** [comment]
I suspect it's because the element containing the text is determined by height, which means the "More" button will always appear below. 

Haven't figured out a solution (read "hack") for this, so would also love to see something along these lines... From UX perspective it's not always clear text is actually cut off as it is now

**Comment by jedfoster** [comment]
See #13, #20, #29, and #120.

[Truncatable](http://www.unheap.com/user-interface/text-links/truncatable/) might do what you want.
