### ISSUE TITLE
As of jQuery 3.0, `this.selector` is depreciated & removed - breaking change

### ISSUE THREAD

**Issue by coreyzev** [jedfoster/Readmore.js#161]
https://github.com/jquery/jquery/issues/1908

https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed

You use this in your code: 

```
$.fn.readmore = function(options) {
    var args = arguments,
        selector = this.selector;
```

Unfortunately on jQuery 3.0 this is no longer valid and returns an `undefined`.

**Comment by jedfoster** [comment]
![7yb49](https://cloud.githubusercontent.com/assets/79984/16437081/955e528c-3d58-11e6-9643-12ef3dc12d3f.jpg)

I appreciate the PR. You're right, it is unfortunate and ugly, but I will take it into consideration.

**Comment by Iangevin** [comment]
https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values

I decided to post it here instead of opening a new issue. With jQuery 3.0, the method .height() can return non-integer values which is use in your code here:

`if ($element.height() <= collapsedHeight) `

I added Math.round on element.height() for a quick fix because the link wouldn't toggle anymore for me and I wanted to keep collapsedHeight with the default value.

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.

**Comment by coreyzev** [comment]
Well that was an unexpected blast from the past. Good to see.
