### ISSUE TITLE
deferred script

### ISSUE THREAD

**Issue by Redani** [jedfoster/Readmore.js#168]
Hi,
All my .js scripts are loaded in the bottom of the page and that causes a little problem when using Readmore, it kindda shows the whole text for a second than hides it. is there a way to fix this?
Thanks a lot for your help and have a great weekend
P.S. I have downloaded your latest version

**Comment by jedfoster** [comment]
Not really. You could try hiding the content of the page by setting `style.display = 'none'` on some container element. For example:

```javascript
document.getElementById('mainContent').style.display = 'none';
```

And then just before you initialize Readmore.js:

```javascript
document.getElementById('mainContent').style.display = 'block';
```

You'd probably want the first bit at the top of the page, somewhere in the `<head>`. Be sure to unhide it before you start Readmore.js, though, otherwise it won't work.

You'd get that kind of FOUC with any library like this.

**Comment by Redani** [comment]
Ok, thank you

**Comment by Redani** [comment]
Hi again,
juste another little question pls:
I'm trying to use embedCSS: false, with my own custom css for the readmore container but it's not working. the link "View More" isn't generated! here is the css I'm using:
`.readmore {
	max-height: none;
	height: 150px;
	transition: height 100ms;
	overflow: hidden;
}`
Is there something I'm missing?
