### ISSUE TITLE
Expanded elements collapse when scrolling on iphone 6 safari and chrome

### ISSUE THREAD

**Issue by D0cNet** [jedfoster/Readmore.js#176]
Hi,
Implemented readmore for long paragraphs. Expand and collapse work fine, however when scrolling the page down on a expanded element (a <p>), it automatically  collapses. 
Debugged my js and did'nt find any triggering of the load event. any idea?

**Comment by ssteigen** [comment]
I'm also having this issue, but it collapses when I scroll up. Scrolling down works fine.

**Comment by ssteigen** [comment]
Actually, I've determined that it's when I change the direction in which I'm scrolling.

If I open it and scroll **up**, that will work but scrolling **down** will make it jump shut.
If I open it and scroll **down**, that will work but scrolling **up** will make it jump shut.

Any updates on this? My best guess was that the version of jquery I was using (1.7) was too old, so I updated it to 1.10, but it didn't seem to help.

**Comment by jorestiq** [comment]
Hello, have you managed to find a solution. I am experiencing the same issue :(

**Comment by git-marijus** [comment]
This issue is related to issue #164 

The aria-expanded value is not set correctly. This value is checked in line 105 if the window is resized (some mobile browsers do this on scroll direction change if the address bar appears/vanishes):
`isExpanded = (current.attr('aria-expanded') === 'true');`
since the value is not set correct the box will be collapsed.

I hotfixed the check like that:
`isExpanded = (current.height() > current.data('collapsedHeight'));`

This resolves the collapsing on scroll (resize) issue. The correct fix would be to properly set the aria-expanded value...

**Comment by ssteigen** [comment]
I added the following styles, which seemed to fix the issue:

```
html, body {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```

These styles are usually used to get around issues with iframes, but I gave it a shot and it worked for me.

**Comment by studentIvan** [comment]
The simple fix is just insert strings below into function resizeBoxes

```javascript
    var innerWidth = $('body').data('innerWidth');
    
    if (innerWidth != $(window).width()) {
        $('body').data('innerWidth', $(window).width());
    } else {
        return false;
    }
```

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS. I believe this issue will be fixed in the next version.

**Comment by kevinblackdesk** [comment]
@jedfoster why wouldn't you merge the pull request https://github.com/jedfoster/Readmore.js/pull/179 by @studentIvan, this fixes the issue. Alot of people are still using version 2, so why wouldn't you just fix it? Instead you're saying f** everybody that uses version 2, just wait till I (production) release version 3?
