### ISSUE TITLE
How to move 'Read More...' inside quote block? 

### ISSUE THREAD

**Issue by k0fi** [jedfoster/Readmore.js#203]
Great plugin. Just wondering, how can I move 

<a href="#" data-readmore-toggle="rmjs-1" aria-controls="rmjs-1">Read More...</a>

to appear _inside_ `<quote class="..."></quote>` ?

 The reason being `quote` has a boundary and distinctive color, and that would be great if `Read More...` link to appear as embedded inside `quote`.

**Comment by sebastianschmid** [comment]
I was wondering the same thing.

Then I found out, that if it was inside, you wouldn't see it, because the element you call readmore() upon will get cut off, because that's why you're using the plugin in the first place ;)

Then again, the readless is inside, probably to make it roll out smooth together with the content. In my book that causes some inconsistencies with margins, as can be seen on the demo page:

http://jedfoster.com/Readmore.js/ -> Artisanal Narwhals

Compressed:

![screen shot 2017-12-05 at 11 56 23](https://user-images.githubusercontent.com/834672/33603590-4ef1f1ac-d9b3-11e7-9c77-25bbabbaaf31.png)


Expanded:

![screen shot 2017-12-05 at 11 56 35](https://user-images.githubusercontent.com/834672/33603604-5ccbc622-d9b3-11e7-8391-51642c2dbf77.png)


I wouldn't really know how to solve this issue, but I hope this at least explains it.
