### ISSUE TITLE
Jquery 3.2.1

### ISSUE THREAD

**Issue by baine101** [jedfoster/Readmore.js#209]
This does not work for Jquery version 3.2.1

**Comment by dajo** [comment]
I can confirm this. It results in overlapping text.

**Comment by tberk** [comment]
To fix overlapping text issue you can apply `overflow: hidden;` to the element.

**Comment by EvyHernyta** [comment]
tberk's answer solved this in my case. Thanks.

**Comment by shiwaretsu** [comment]
It is because readmore.js uses the [.selector property](https://api.jquery.com/selector/), which has been [removed](https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed) in jQuery 3.

The answer from @tberk works if you only cares about the design, but unfortunately not with other options, like `afterToggle`.

For now, I modified [the lines](https://github.com/jedfoster/Readmore.js/blob/master/readmore.js#L314)
```
var args = arguments,
  selector = this.selector;
```
by
```
var args = arguments;
var selector = this.selector == null ? '' : this.selector;
```
@jedfoster Is it a good solution? I was not able to find a case where `this.selector` returns anything else than an empty string anyway.

**Comment by hempels** [comment]
Pull request: #206

**Comment by jedfoster** [comment]
Version 3.0 of Readmore.js will drop jQuery entirely, in favor of vanilla JS.
