### ISSUE TITLE
Feature :: line-height 

### ISSUE THREAD

**Issue by K-Q-J** [jedfoster/Readmore.js#221]
Hi @jedfoster, nice plugin love it 👍 
still tho could you consider the line-height feature 💯 

As you know now you can set height in `collapsedHeight` but it is not perfect as you have to set it exactly where the line should end, you will get something like this:
![Image of collapsedHeight](https://screenshots.mrkreativ.de/screenshots/whafes_3366998/2018-06-29-l59ul-12-23-39.png)

- but what it should be is that, it calculate the height relatively to closest line-height  
```javascript
$('.js-readmore').readmore({collapsedHeight: 200, lineHeight: true });
```

Example 
```css
p { line-height:  28px; font-size: 22px; }
```
`collapsedHeight` is set to 200
::::::::::
` 28 * X = 200 `
`X = 200 / 28 `
`X = 7.14 `
so it should be 7 lines 
now the height should be 
`7 * 28 = 196px `

:fire::fire: that's all, Have fun! :fire::fire:

**Comment by jedfoster** [comment]
Calculating based on line-height _would_ be great feature, but would really only work if _all_ lines of text have the same height, but headings (`h1`, `h2`, etc.) typically have line heights that differ from paragraphs (`p`). A well designed page might adhere to a strict horizontal scale, but I don't expect that Readmore.js will only be used on such pages.

In order to keep Readmore.js' interface simple, I will not implement this feature. It would be a (relatively) trivial matter to perform such line-height calculations in your own code and supply the resulting value in your Readmore.js configuration.
