### ISSUE TITLE
Work in Modal ?

### ISSUE THREAD

**Issue by boadude** [jedfoster/Readmore.js#84]
No working in Modal dialog box?

**Comment by jedfoster** [comment]
Code example? Gist? There are _many, many_ ways to do a modal dialog.

**Comment by boadude** [comment]
Here... just and example... http://jsfiddle.net/kcS2N/44/

**Comment by iamw00t** [comment]
I had a similar problem using it within tabs, where the "tabbed content" has a height of 0, I suspect it's because it is hidden. I worked around this by adding another option to the constructor that I add to the data object, then in setBoxHeights I check if the object is visible, if not I use the height from said object.
For Example:
 $('.rd-more').readmore({
   hiddenHeight:$("#foo").outerHeight()
})

Line 70: (setBoxHeights)
expandedHeight = (el.is(":visible"))? el.outerHeight(): element.data('hiddenHeight'),

Line 153: (Readmore)
        $(this.element).data({
            defaultHeight: this.options.collapsedHeight,
            heightMargin: this.options.heightMargin,
            hiddenHeight: this.options.hiddenHeight
        });
Hope that helps

**Comment by jedfoster** [comment]
I can confirm that this is because the modal content has a height of 0. Calculating height for a hidden element, especially when it is hidden by an unknown ancestor, is outside the scope of Readmore.js. @iamw00t's solution is probably best, but it's not appropriate for inclusion in this project.
